name: Content Suggestion
description: Suggest new content or improvements for the book
title: "[Suggestion]: "
labels: ["suggestion", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest improvements to the Agentic Workflows Book!
        
        This book is self-maintaining, so relevant suggestions will be automatically processed.
        
  - type: dropdown
    id: category
    attributes:
      label: Content Category
      description: Which area does your suggestion relate to?
      options:
        - Agentic Workflows
        - Agent Orchestration
        - Agentic Scaffolding
        - Skills and Tools
        - GitHub Agentic Workflows (GH-AW)
        - GitHub Agents (Copilot, Coding Agent)
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: type
    attributes:
      label: Suggestion Type
      description: What type of change are you suggesting?
      options:
        - New Content
        - Improvement to Existing Content
        - Correction/Fix
        - Example or Tutorial
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your suggestion in detail
      placeholder: What would you like to see added or changed?
    validations:
      required: true
      
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this suggestion valuable?
      placeholder: How would this improve the book?
    validations:
      required: false
      
  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Any examples, code snippets, or references that would help
      placeholder: Links, code examples, etc.
    validations:
      required: false
